version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
        
  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0

volumes:
  redis:

  